// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHe5wyi5a688dIrl3iX-V9IDhjs5Htyi8',
    appId: '1:365693745251:web:faceb5474c9b4782bc6056',
    messagingSenderId: '365693745251',
    projectId: 'vocamate-8ac50',
    authDomain: 'vocamate-8ac50.firebaseapp.com',
    storageBucket: 'vocamate-8ac50.firebasestorage.app',
    measurementId: 'G-BSKTHLKX6C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm89w6d5fJraTVu6i3UWsuy2Oqnur-Kbc',
    appId: '1:365693745251:android:9e5c734bc28b20a4bc6056',
    messagingSenderId: '365693745251',
    projectId: 'vocamate-8ac50',
    storageBucket: 'vocamate-8ac50.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsJU_VrtuhyBGrpDflup9cc5Q9rtGq5bo',
    appId: '1:365693745251:ios:4106496c6b93a42bbc6056',
    messagingSenderId: '365693745251',
    projectId: 'vocamate-8ac50',
    storageBucket: 'vocamate-8ac50.firebasestorage.app',
    iosBundleId: 'com.example.aiMemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsJU_VrtuhyBGrpDflup9cc5Q9rtGq5bo',
    appId: '1:365693745251:ios:4106496c6b93a42bbc6056',
    messagingSenderId: '365693745251',
    projectId: 'vocamate-8ac50',
    storageBucket: 'vocamate-8ac50.firebasestorage.app',
    iosBundleId: 'com.example.aiMemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHe5wyi5a688dIrl3iX-V9IDhjs5Htyi8',
    appId: '1:365693745251:web:8af257754d43f350bc6056',
    messagingSenderId: '365693745251',
    projectId: 'vocamate-8ac50',
    authDomain: 'vocamate-8ac50.firebaseapp.com',
    storageBucket: 'vocamate-8ac50.firebasestorage.app',
    measurementId: 'G-4BC33C2JW4',
  );
}
